version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env
    ports:
      - "8080:8080"
    depends_on:
      - external
    container_name: cariad

  external:
    image: emanuelschmoczer/coding-challenge-test-server:latest
    hostname: servers
    ports:
      - "8090:8090"
